version: '2'
services:
 hazelcast:
   image: hazelcast/hazelcast:3.12.5
   hostname: hdfcmf-prod-hazelcast
   container_name: hdfcmf-prod-hazelcast
   restart: always
   #command: tail -F /dev/null
   ports:
     - 5701:5701
   environment:
     JAVA_OPTS: "-Dhazelcast.config=/opt/hazelcast/config_ext/hazelcast.xml"
   volumes:
       - ./conf:/opt/hazelcast/config_ext
 mancenter:
   image: hazelcast/management-center:3.12.8
   hostname: hdfcmf-prod-mancenter
   container_name: hdfcmf-prod-mancenter
   restart: always
   environment:
     MC_INIT_CMD: "./mc-conf.sh create-user -H=/data -n=hdfc-prod -p=hdfc@371 -r=admin -v"
   ports:
     - 8081:8080
volumes:
    hazelcast-conf:
        driver: local
